### ISSUE TITLE
prompt messed up when ansi escape codes are used

### ISSUE THREAD

**Issue by sammy-ette** [deadsy/go-cli#1]
illustrated:
![](https://modeus.is-inside.me/8sSqrnpl.png)

if the prompt includes ansi escape codes, go-cli will count that as prompt length (when it really shouldnt)

a better example:
![](https://modeus.is-inside.me/EmB6QFLF.png)
(notice where the cursor is)

**Comment by deadsy** [comment]
Not entirely sure I want to support general ansi escape sequences in the prompt string - the length calculation is already tricky because it's a utf-8 sting and you have to work out the length of that. What if there were support for setting the prompt color?

**Comment by sammy-ette** [comment]
wouldn't it be better to just strip ansi sequences from the prompt when trying to get its length?
